// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd_FVHOTPnvfwGTEKFqbgKw2VlZWRyo4U',
    appId: '1:920740673623:web:09617daedbbb9719848b12',
    messagingSenderId: '920740673623',
    projectId: 'money-tracking-2ec2d',
    authDomain: 'money-tracking-2ec2d.firebaseapp.com',
    storageBucket: 'money-tracking-2ec2d.firebasestorage.app',
    measurementId: 'G-701KL53RZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsgsGyRL018C5yVDHN8VBryhRwvLsq2zI',
    appId: '1:920740673623:android:fcea5873bf951be5848b12',
    messagingSenderId: '920740673623',
    projectId: 'money-tracking-2ec2d',
    storageBucket: 'money-tracking-2ec2d.firebasestorage.app',
  );

  // Desktop platforms use the Firebase Web app configuration.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd_FVHOTPnvfwGTEKFqbgKw2VlZWRyo4U',
    appId: '1:920740673623:web:09617daedbbb9719848b12',
    messagingSenderId: '920740673623',
    projectId: 'money-tracking-2ec2d',
    authDomain: 'money-tracking-2ec2d.firebaseapp.com',
    storageBucket: 'money-tracking-2ec2d.firebasestorage.app',
    measurementId: 'G-701KL53RZ0',
  );
}
